### ISSUE TITLE
E01 Image Data not showing in Mount point

### ISSUE THREAD

**Issue by BuckPete** [ralphje/imagemounter#31]
Running ImageMounter.py -s -e and it seems to run through the procedure fine.

Terminal tells me EWF1 mounted fine to my mount point

I can see the EWF1 file in the ewf_2018_xx_xx_xx-xx_xx directory has been created.

#EWF1 file tells us its a DOS/MBR boot sector and NFTS

I can see that my mount directory is active (green) but no image data whatsover within. (ls -a)

I can also umount the same mount directory without error, so something is in there, just can't see it.  I have tried mounting to several different mount points in different locations. Get same issue.

Using the ever so slightly longer method of Mounting the same E01 file using ewfmount works fine and I can see image data in destination mount directory.

I would really like this to work though as it's cool.

Thanks.

Pete
(massive UK Newbie - sorry)

**Comment by ralphje** [comment]
Is it possible for you to provide imount's full output with full verbosity (-vvvv) so I can look into this matter?

**Comment by BuckPete** [comment]
Hi Ralph

How is this achieved please?  I am still finding my way around Linux

sorry again.

**Comment by ralphje** [comment]
Seeing the command you included, ``ImageMounter.py -s -e``, this looks a lot like you are using Sift Workstation and its included script (https://github.com/sans-dfir/sift-files/blob/master/scripts/imageMounter.py). Perhaps confusingly, this project is not affiliated with that specific script. It is completely separate. If you need help using that script, please contact the developers of Sift Workstation or the instructors of the related SANS course instead.

If you'd like to use this repository's version, please follow the instructions to install this project in the documentation. Perhaps you'll need some help figuring this all out, but something like ``sudo pip3 install imagemounter`` should get you started. You'll be provided with the ``imount`` command line utility. Running ``sudo imount disk_image.e01`` should mount the disk image, and ``sudo imount disk_image.e01 -vvvv`` would have given you the verbosity level I requested to help debugging your issue. (But that is irrelevant now 😄 .)

Since your issue pertains to another project, I'm closing this issue. If you've found an issue with my project, please open a new issue.
